# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 03:00
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_weekday', models.CharField(choices=[('sun', 'Sunday'), ('mon', 'Monday'), ('tues', 'Tuesday'), ('wed', 'Wednesday'), ('thurs', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday')], max_length=5)),
                ('start_month', models.CharField(choices=[('jan', 'January'), ('feb', 'February'), ('mar', 'March'), ('apr', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('aug', 'August'), ('sept', 'September'), ('oct', 'October'), ('nov', 'November'), ('dec', 'December')], max_length=4)),
                ('start_day', models.IntegerField()),
                ('start_minutes', models.IntegerField()),
                ('end_weekday', models.CharField(choices=[('sun', 'Sunday'), ('mon', 'Monday'), ('tues', 'Tuesday'), ('wed', 'Wednesday'), ('thurs', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday')], max_length=5)),
                ('end_month', models.CharField(choices=[('jan', 'January'), ('feb', 'February'), ('mar', 'March'), ('apr', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('aug', 'August'), ('sept', 'September'), ('oct', 'October'), ('nov', 'November'), ('dec', 'December')], max_length=4)),
                ('end_day', models.IntegerField()),
                ('end_minutes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ParkingRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.CharField(max_length=200)),
                ('rule_type', models.CharField(choices=[('ypark', 'Parking Allowed'), ('npark', 'Parking Prohibited'), ('ystand', 'Standing Allowed'), ('nstand', 'Standing Prohibited'), ('ystop', 'Stopping Allowed'), ('nstop', 'Stopping Prohibited')], max_length=6)),
                ('section_id', models.CharField(max_length=12)),
                ('street_segment', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('time_limit', models.IntegerField(blank=True, default=None, null=True)),
                ('date_ranges', models.ManyToManyField(to='nyc.DateRange')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('pr', 'Private'), ('cm', 'Commercial'), ('tr', 'Truck')], max_length=2, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='parkingrule',
            name='exclusive_vehicles',
            field=models.ManyToManyField(to='nyc.Vehicle'),
        ),
    ]
