# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 03:00
from __future__ import unicode_literals

from django.db import migrations

from ..models import Vehicle as V


def create_vehicles(apps, schema_editor):
    Vehicle = apps.get_model('nyc', 'Vehicle')

    for (vehicle_type_key, _) in V.VEHICLE_TYPES:
        v = Vehicle()
        v.vehicle_type = vehicle_type_key
        v.save()


class Migration(migrations.Migration):

    dependencies = [
        ('nyc', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_vehicles),
    ]
